name 'windows_patch_compliance'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures windows_patch_compliance'
long_description 'Installs/Configures windows_patch_compliance'
version '0.1.0'
